spring:
  application:
    name: OrderService

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/order_db33

    driver-class-name: org.postgresql.Driver
server:
  port: 7777

user_service:
  url: http://localhost:4444/users